last commit

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -1,3 +1,10 @@
+name: Build and Release APK
+
+on:
+  push:
+    branches:
+      - master  # Change this to match your branch, or add more branches as needed
+
 jobs:
   build:
     permissions: write-all # this is the FIX
@@ -7,6 +14,7 @@ jobs:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0 # Ensures tags are fetched
+
 
       - name: Set up JDK 11
         uses: actions/setup-java@v2
@@ -22,20 +30,14 @@ jobs:
       - name: Build APK
         run: flutter build apk --release
 
-      - name: Configure Git
+      - name: Create Tag
         run: |
-          git config --local user.email "abiha9480@gmail.com
-          git config --local user.name "abolfazlirani"
+          TAG_NAME=$(date +'%Y%m%d%H%M%S')
+          echo "Creating tag $TAG_NAME"
+          git tag $TAG_NAME
+          git push origin $TAG_NAME || echo "Failed to push tag $TAG_NAME" >&2
+          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
 
-      - name: Tag the repository
-        id: tag
-        run: |
-          # See https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names
-          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
-          echo "$TAG"
-          echo "tag=$TAG" >> $GITHUB_OUTPUT
-          git tag -a $TAG -m "Published version $TAG" ${GITHUB_SHA}
-          git push origin $TAG
 
       - name: Upload APK to GitHub Releases
         uses: softprops/action-gh-release@v1
